### ISSUE TITLE
Error when run Colab notebook

### ISSUE THREAD

**Issue by wt12318** [dina-lab3D/Fold-Dock#2]
Hi,
Thanks for the tool. I have tried the Colab, but in the `Predict antibody-antigen complexes` step, it has following error:

```
Loading the trained models
Traceback (most recent call last):
  File "/content/Fold-Dock/fold_dock.py", line 207, in <module>
    dock_and_fold_batch(args.ab_fasta, input_ag_pdb, args.antigen_chains, dock_model, ab_score_model,
  File "/content/Fold-Dock/fold_dock.py", line 106, in dock_and_fold_batch
    dock = tf.keras.models.load_model(dock, compile=False)
  File "/usr/local/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 204, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=/content/Fold-Dock/DockModel. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(/content/Fold-Dock/DockModel, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).

```

**Comment by duhovka** [comment]
Hi,

I suggest you try a web server: https://folddock.cs.huji.ac.il/
